# Generated by Django 3.2.13 on 2022-06-14 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('CountryCode', models.CharField(db_column='CountryCode', max_length=2, primary_key=True, serialize=False)),
                ('CountryName', models.CharField(db_column='CountryName', max_length=80)),
                ('CountryDisplayName', models.CharField(db_column='CountryDisplayName', max_length=80)),
                ('TimeZoneName', models.CharField(db_column='TimeZoneName', max_length=80, null=True)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('PostTypeID', models.AutoField(db_column='PostTypeID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountrySubdivision',
            fields=[
                ('CountrySubdivisionCode', models.CharField(db_column='CountrySubdivisionCode', max_length=6, primary_key=True, serialize=False)),
                ('SubdivisonCode', models.CharField(db_column='SubdivisonCode', max_length=3)),
                ('CountrySubdivisionName', models.CharField(db_column='CountrySubdivisionName', max_length=80)),
                ('CountrySubdivisionDisplayName', models.CharField(db_column='CountrySubdivisionDisplayName', max_length=80)),
                ('CountryCode', models.ForeignKey(db_column='CountryCode', on_delete=django.db.models.deletion.DO_NOTHING, to='services.country')),
            ],
            options={
                'db_table': 'CountrySubdivision',
                'unique_together': {('CountryCode', 'SubdivisonCode')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('CityID', models.AutoField(db_column='CityID', primary_key=True, serialize=False)),
                ('CityName', models.CharField(db_column='CityName', max_length=200)),
                ('CountryCode', models.ForeignKey(db_column='CountryCode', on_delete=django.db.models.deletion.DO_NOTHING, to='services.country')),
                ('CountrySubdivisionCode', models.ForeignKey(db_column='CountrySubdivisionCode', on_delete=django.db.models.deletion.DO_NOTHING, to='services.countrysubdivision')),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='ApplicationLoginActivity',
            fields=[
                ('ApplicationLoginActivityID', models.AutoField(db_column='ApplicationLoginActivityID', primary_key=True, serialize=False)),
                ('IPAddress', models.CharField(db_column='IPAddress', max_length=39)),
                ('LoginTimestamp', models.DateTimeField(auto_now_add=True, db_column='LoginTimestamp')),
                ('CityID', models.ForeignKey(db_column='CityID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.city')),
                ('UserID', models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ApplicationLoginActivity',
            },
        ),
    ]
